# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 33751704f662088c09d640448b266c97dd5f2a410aae0bd6bd2e56310ff95d8e68e0eecebed6f08a1ac64749583e137099bad53d7b7ebee7f8479532ef128a3f

test:
  secret_key_base: be51123d98e12307cdff6bde19417628d2d540b579e505fb6e99d768e6e12ad083cfe00f266c42266a6aa6730f1a6efd999fc43cd9e9658316ea905b4e28204a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
